# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 07:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=34)),
                ('statecode', models.CharField(max_length=4)),
            ],
            options={
                'managed': False,
                'db_table': 'agency',
            },
        ),
        migrations.CreateModel(
            name='AlarmLevel',
            fields=[
                ('alarmlevel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.IntegerField()),
                ('id_911', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'alarmlevel',
            },
        ),
        migrations.CreateModel(
            name='FireBlock',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid_1', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('objectid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('resp_zone', models.CharField(blank=True, max_length=6, null=True)),
                ('jurisdict', models.CharField(blank=True, max_length=2, null=True)),
                ('dist_grp', models.CharField(blank=True, max_length=2, null=True)),
                ('notes', models.CharField(blank=True, max_length=60, null=True)),
                ('of_fma', models.CharField(blank=True, max_length=26, null=True)),
                ('mv_label', models.CharField(blank=True, max_length=15, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'managed': False,
                'db_table': 'fblocks',
            },
        ),
        migrations.CreateModel(
            name='FMA',
            fields=[
                ('fma', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'managed': False,
                'db_table': 'fma_shapes',
            },
        ),
        migrations.CreateModel(
            name='FMAStats',
            fields=[
                ('fma', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('fma_population_total', models.IntegerField(blank=True, null=True)),
                ('percent_owner_occ_hh', models.FloatField(blank=True, null=True)),
                ('percent_renter_occ_hh', models.FloatField(blank=True, null=True)),
                ('median_hh_income', models.IntegerField(blank=True, null=True)),
                ('percent_w_hinsurance', models.FloatField(blank=True, null=True)),
                ('percent_wo_hinsurance', models.FloatField(blank=True, null=True)),
                ('percent_college_grad_or_higher', models.FloatField(blank=True, null=True)),
                ('percent_rec_fs', models.FloatField(blank=True, null=True)),
                ('percent_total_lesh', models.FloatField(blank=True, null=True)),
                ('percent_non_white', models.FloatField(blank=True, null=True)),
                ('percent_below_pov', models.FloatField(blank=True, null=True)),
                ('percent_member_65plus', models.FloatField(blank=True, null=True)),
                ('percent_diff_area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'fma_api_rollup',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.IntegerField(primary_key=True, serialize=False)),
                ('deptrespond_id', models.IntegerField(blank=True, null=True)),
                ('runnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('incdate', models.DateField(blank=True, null=True)),
                ('foundsituation', models.IntegerField(blank=True, null=True)),
                ('callreceived_id', models.IntegerField(blank=True, null=True)),
                ('censustract', models.CharField(blank=True, max_length=6, null=True)),
                ('fmarespcomp', models.CharField(blank=True, max_length=10, null=True)),
                ('career', models.IntegerField(blank=True, null=True)),
                ('engresp', models.IntegerField(blank=True, null=True)),
                ('aaresp', models.IntegerField(blank=True, null=True)),
                ('medresp', models.IntegerField(blank=True, null=True)),
                ('othervehiclesresp', models.IntegerField(blank=True, null=True)),
                ('firstonscene', models.CharField(blank=True, max_length=10, null=True)),
                ('quad', models.CharField(blank=True, max_length=2, null=True)),
                ('streettype', models.CharField(blank=True, max_length=4, null=True)),
                ('streetname', models.CharField(blank=True, max_length=30, null=True)),
                ('quad2', models.CharField(blank=True, max_length=4, null=True)),
                ('streetname2', models.CharField(blank=True, max_length=30, null=True)),
                ('streettype2', models.CharField(blank=True, max_length=4, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('neighborassoc', models.CharField(blank=True, max_length=20, null=True)),
                ('fireblock', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'incident',
            },
        ),
        migrations.CreateModel(
            name='IncidentTimes',
            fields=[
                ('inctimes_id', models.IntegerField(primary_key=True, serialize=False)),
                ('incident_id', models.IntegerField(blank=True, null=True)),
                ('responder_id', models.IntegerField(blank=True, null=True)),
                ('realtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'inctimes',
            },
        ),
        migrations.CreateModel(
            name='IncsitFound',
            fields=[
                ('incsitfound_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('statecode', models.CharField(blank=True, max_length=3, null=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
                ('inactive', models.IntegerField(blank=True, null=True)),
                ('nfirs', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'incsitfound',
            },
        ),
        migrations.CreateModel(
            name='IncsitFoundClass',
            fields=[
                ('incsitfoundclass_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'incsitfoundclass',
            },
        ),
        migrations.CreateModel(
            name='IncsitFoundSub',
            fields=[
                ('incsitfoundsub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'incsitfoundsub',
            },
        ),
        migrations.CreateModel(
            name='MutualAid',
            fields=[
                ('mutualaid_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('inactive', models.IntegerField(blank=True, null=True)),
                ('nfirs', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'mutualaid',
            },
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('incident_id', models.IntegerField(primary_key=True, serialize=False)),
                ('responder_id', models.IntegerField()),
                ('codetosc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'responder',
            },
        ),
        migrations.CreateModel(
            name='ResponderUnit',
            fields=[
                ('responderunit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('id_911', models.CharField(blank=True, max_length=6, null=True)),
                ('translateto', models.CharField(blank=True, max_length=50, null=True)),
                ('process', models.IntegerField(blank=True, null=True)),
                ('versaterm', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'responderunit',
            },
        ),
        migrations.CreateModel(
            name='SituationFound',
            fields=[
                ('situationfound_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('review', models.IntegerField(blank=True, null=True)),
                ('inactive', models.IntegerField(blank=True, null=True)),
                ('nemsis', models.CharField(blank=True, max_length=10, null=True)),
                ('e09_15', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'situationfound',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='TimeDesc',
            fields=[
                ('timedesc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('id_911', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'timedesc',
            },
        ),
        migrations.CreateModel(
            name='TypeNatureCode',
            fields=[
                ('typenaturecode_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('id_911', models.CharField(blank=True, max_length=15, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('nemsis', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'typenaturecode',
            },
        ),
    ]
