# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-02 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('statecode', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'agency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlarmLevel',
            fields=[
                ('alarmlevel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('id_911', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'alarmlevel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensusTract',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('statefp', models.CharField(blank=True, max_length=2, null=True)),
                ('countyfp', models.CharField(blank=True, max_length=3, null=True)),
                ('tractce', models.CharField(blank=True, max_length=6, null=True)),
                ('blkgrpce', models.CharField(blank=True, max_length=1, null=True)),
                ('geoid', models.CharField(blank=True, max_length=12, null=True)),
                ('namelsad', models.CharField(blank=True, max_length=13, null=True)),
                ('mtfcc', models.CharField(blank=True, max_length=5, null=True)),
                ('funcstat', models.CharField(blank=True, max_length=1, null=True)),
                ('aland', models.FloatField(blank=True, null=True)),
                ('awater', models.FloatField(blank=True, null=True)),
                ('intptlat', models.CharField(blank=True, max_length=11, null=True)),
                ('intptlon', models.CharField(blank=True, max_length=12, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'censustract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FireBlock',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid_1', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('objectid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fma', models.CharField(blank=True, max_length=2, null=True)),
                ('resp_zone', models.CharField(blank=True, max_length=6, null=True)),
                ('jurisdict', models.CharField(blank=True, max_length=2, null=True)),
                ('dist_grp', models.CharField(blank=True, max_length=2, null=True)),
                ('notes', models.CharField(blank=True, max_length=60, null=True)),
                ('of_fma', models.CharField(blank=True, max_length=26, null=True)),
                ('mv_label', models.CharField(blank=True, max_length=15, null=True)),
                ('shape_star', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_stle', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fireblock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FireStation',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('station', models.CharField(blank=True, max_length=6, null=True)),
                ('address', models.CharField(blank=True, max_length=38, null=True)),
                ('city', models.CharField(blank=True, max_length=28, null=True)),
                ('district', models.CharField(blank=True, max_length=40, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'firestation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FMA',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('fma', models.CharField(blank=True, max_length=26, null=True)),
                ('mv_label', models.CharField(blank=True, max_length=15, null=True)),
                ('shape_star', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_stle', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.IntegerField(primary_key=True, serialize=False)),
                ('deptrespond_id', models.IntegerField(blank=True, null=True)),
                ('runnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('incdate', models.DateField(blank=True, null=True)),
                ('foundsituation', models.IntegerField(blank=True, null=True)),
                ('callreceived_id', models.IntegerField(blank=True, null=True)),
                ('censustract', models.CharField(blank=True, max_length=6, null=True)),
                ('fmarespcomp', models.CharField(blank=True, max_length=6, null=True)),
                ('career', models.IntegerField(blank=True, null=True)),
                ('engresp', models.IntegerField(blank=True, null=True)),
                ('aaresp', models.IntegerField(blank=True, null=True)),
                ('medresp', models.IntegerField(blank=True, null=True)),
                ('othervehiclesresp', models.IntegerField(blank=True, null=True)),
                ('firstonscene', models.CharField(blank=True, max_length=10, null=True)),
                ('quad', models.CharField(blank=True, max_length=2, null=True)),
                ('streettype', models.CharField(blank=True, max_length=4, null=True)),
                ('streetname', models.CharField(blank=True, max_length=30, null=True)),
                ('quad2', models.CharField(blank=True, max_length=2, null=True)),
                ('streetname2', models.CharField(blank=True, max_length=30, null=True)),
                ('streettype2', models.CharField(blank=True, max_length=4, null=True)),
                ('county', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=9, null=True)),
                ('neighborassoc', models.CharField(blank=True, max_length=18, null=True)),
                ('fireblock', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncsitFound',
            fields=[
                ('incsitfound_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('statecode', models.CharField(blank=True, max_length=3, null=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
                ('inactive', models.IntegerField(blank=True, null=True)),
                ('nfirs', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'incsitfound',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncsitFoundClass',
            fields=[
                ('incsitfoundclass_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incsitfoundclass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncsitFoundSub',
            fields=[
                ('incsitfoundsub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('incsitfoundclass', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('sortorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incsitfoundsub',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncTimes',
            fields=[
                ('inctimes_id', models.IntegerField(primary_key=True, serialize=False)),
                ('realtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inctimes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MutualAid',
            fields=[
                ('mutualaid_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('inactive', models.IntegerField(blank=True, null=True)),
                ('nfirs', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'mutualaid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.IntegerField()),
                ('responder_id', models.IntegerField()),
                ('codetosc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'responder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponderUnit',
            fields=[
                ('responderunit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('id_911', models.CharField(blank=True, max_length=6, null=True)),
                ('translateto', models.CharField(blank=True, max_length=50, null=True)),
                ('process', models.IntegerField(blank=True, null=True)),
                ('versaterm', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'responderunit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SituationFound',
            fields=[
                ('situationfound_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('review', models.IntegerField(blank=True, null=True)),
                ('inactive', models.IntegerField(blank=True, null=True)),
                ('nemsis', models.CharField(blank=True, max_length=10, null=True)),
                ('e09_15', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'situationfound',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeDesc',
            fields=[
                ('timedesc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('id_911', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'timedesc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeNatureCode',
            fields=[
                ('typenaturecode_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('id_911', models.CharField(blank=True, max_length=8, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('nemsis', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'typenaturecode',
                'managed': False,
            },
        ),
    ]
