# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-23 03:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusBlocks',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('statefp', models.CharField(blank=True, max_length=2, null=True)),
                ('countyfp', models.CharField(blank=True, max_length=3, null=True)),
                ('tractce', models.CharField(blank=True, max_length=6, null=True)),
                ('blkgrpce', models.CharField(blank=True, max_length=1, null=True)),
                ('geoid', models.CharField(blank=True, max_length=12, null=True)),
                ('namelsad', models.CharField(blank=True, max_length=13, null=True)),
                ('mtfcc', models.CharField(blank=True, max_length=5, null=True)),
                ('funcstat', models.CharField(blank=True, max_length=1, null=True)),
                ('aland', models.FloatField(blank=True, null=True)),
                ('awater', models.FloatField(blank=True, null=True)),
                ('intptlat', models.CharField(blank=True, max_length=11, null=True)),
                ('intptlon', models.CharField(blank=True, max_length=12, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4269)),
            ],
            options={
                'db_table': 'ceblocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensusHouseholdIncome',
            fields=[
                ('id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('id2', models.CharField(max_length=12)),
                ('geography', models.CharField(max_length=60)),
                ('estimate_total', models.IntegerField()),
                ('total_less_than_10000', models.IntegerField()),
                ('total_10000_to_14999', models.IntegerField()),
                ('total_15000_to_19999', models.IntegerField()),
                ('total_20000_to_24999', models.IntegerField()),
                ('total_25000_to_29999', models.IntegerField()),
                ('total_30000_to_34999', models.IntegerField()),
                ('total_35000_to_39999', models.IntegerField()),
                ('total_40000_to_44999', models.IntegerField()),
                ('total_45000_to_49999', models.IntegerField()),
                ('total_50000_to_59999', models.IntegerField()),
                ('total_60000_to_74999', models.IntegerField()),
                ('total_75000_to_99999', models.IntegerField()),
                ('total_100000_to_124999', models.IntegerField()),
                ('total_125000_to_149999', models.IntegerField()),
                ('total_150000_to_199999', models.IntegerField()),
                ('total_200000_or_more', models.IntegerField()),
            ],
            options={
                'db_table': 'census_household_income',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensusHouseholdLanguage',
            fields=[
                ('id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('id2', models.CharField(max_length=12)),
                ('geography', models.CharField(max_length=60)),
                ('estimate_total', models.IntegerField()),
                ('english_only', models.IntegerField()),
                ('spanish_total', models.IntegerField()),
                ('spanish_lesh', models.IntegerField()),
                ('spanish_notlesh', models.IntegerField()),
                ('other_indo_euro_total', models.IntegerField()),
                ('other_indo_euro_lesh', models.IntegerField()),
                ('other_indo_euro_notlesh', models.IntegerField()),
                ('asian_pacific_island_total', models.IntegerField()),
                ('asian_pacific_island_lesh', models.IntegerField()),
                ('asian_pacific_island_notlesh', models.IntegerField()),
                ('other_total', models.IntegerField()),
                ('other_lesh', models.IntegerField()),
                ('other_notlesh', models.IntegerField()),
            ],
            options={
                'db_table': 'census_household_language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensusHouseholds65Plus',
            fields=[
                ('id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('id2', models.CharField(max_length=12)),
                ('geography', models.CharField(max_length=60)),
                ('totals', models.IntegerField()),
                ('oneplus_people_65plus', models.IntegerField()),
                ('one_or_more_people_65plus_1_person', models.IntegerField()),
                ('oneplus_people_65plus_2plus_person', models.IntegerField()),
                ('oneplus_people_65plus_2plus_person_family', models.IntegerField()),
                ('oneplus_people_65plus_2plus_person_nonfamily', models.IntegerField()),
                ('no_people_65plus', models.IntegerField()),
                ('no_people_65plus_1_person', models.IntegerField()),
                ('no_people_65plus_2plus_person', models.IntegerField()),
                ('no_people_65plus_2plus_person_family', models.IntegerField()),
                ('no_people_65plus_2plus_person_nonfamily', models.IntegerField()),
            ],
            options={
                'db_table': 'census_households_65plus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensusHousingTenure',
            fields=[
                ('id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('id2', models.CharField(max_length=12)),
                ('geography', models.CharField(max_length=60)),
                ('estimate_total_households', models.IntegerField()),
                ('estimate_total_owner_occupied', models.IntegerField()),
                ('estimate_total_renter_occupied', models.IntegerField()),
            ],
            options={
                'db_table': 'census_housing_tenure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensusMedianHouseholdIncome',
            fields=[
                ('id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('id2', models.CharField(max_length=12)),
                ('geography', models.CharField(max_length=60)),
                ('estimate_median_household_income', models.IntegerField()),
            ],
            options={
                'db_table': 'census_median_household_income',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensusRace',
            fields=[
                ('id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('id2', models.CharField(max_length=12)),
                ('geography', models.CharField(max_length=60)),
                ('total', models.IntegerField()),
                ('white_alone', models.IntegerField()),
                ('black_alone', models.IntegerField()),
                ('american_indian_alaska_native_alone', models.IntegerField()),
                ('asian_alone', models.IntegerField()),
                ('native_hawaiian_pacific_islander_alone', models.IntegerField()),
                ('some_other_alone', models.IntegerField()),
                ('two_or_more_races', models.IntegerField()),
                ('two_or_more_some_other', models.IntegerField()),
                ('two_or_more_excluding_some_other_three_or_more_races', models.IntegerField()),
            ],
            options={
                'db_table': 'census_race',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensusTotalPopulation',
            fields=[
                ('id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('id2', models.CharField(max_length=12)),
                ('geography', models.CharField(max_length=60)),
                ('estimate_total', models.IntegerField()),
            ],
            options={
                'db_table': 'census_total_population',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='fireblock',
            table='fblocks',
        ),
    ]
